### PR TITLE
Added .NET Code execution from UI

### PR DESCRIPTION
**Pull request by ooojustin**
This feature gives users the ability to write their own code in the UI and execute it on a clients machine automatically. Code is compiled via CodeDom and then uploaded/executed via the existing DoUploadAndExecute command.

Option in UI:
Option in UI

New form:
New form

### CODE REVIEW

**Comment by ooojustin** [comment]
@MaxXor It's been > 2 months. Are you no longer maintaining the project?

**Comment by perscriptions** [comment]
Good request, forever waiting for approval

**Comment by haxpak** [comment]
any plan for merging? 
@MaxXor

**Comment by ooojustin** [comment]
I'm not sure why this still hasn't been merged.
It doesn't seem the project has been abandoned.

**Comment by MaxXor** [comment]
@ooojustin Can you rebase against latest master branch?

**Review by yezz123 — APPROVED** [review]

**Comment by StarBoyzz** [comment]
Has this been added to the main project yet?

**Pull request closed without merging**
